name: Check bump versions
on:
  schedule:
  - cron: "0 6 * * 5"
  push:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: '0'

      - name: Install dependencies and bump versions
        run: |
          yarn install
          yarn backstage-cli versions:bump
      - name: Get current date
        run: echo '::set-output name=date::$(date +'%Y-%m-%d')'
        steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          commit-message: Update dependencies
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-dependencies-${{ steps.current-time.outputs.formattedTime }}
          delete-branch: true
          title: 'Update dependencies'
          base: main
          body: |
            Update backstage dependencies
            - Updated using backstage-cli versions:bump
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            dependency
            update
            automated pr
          draft: false
