name: Check bump versions
on:
  schedule:
    - cron: '0 6 * * 5'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install dependencies and bump versions
        run: |
          yarn install
          yarn backstage-cli versions:bump
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH-MM
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN  }}
          commit-message: Update dependencies
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-dependencies-${{ steps.current-time.outputs.formattedTime }}
          delete-branch: true
          title: 'Update Dependencies - plugins'
          base: main
          body: |
            Update backstage dependencies
            - Updated using backstage-cli versions:bump
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            dependency
            update
            automated pr
          draft: false
